import type { GenerationAgentOutput } from '../../../agents/generationSchedulingRules';
import type { SectionGenerationState } from '../build/protocolBuildConsoleStore';
import { getKnowledgeGraph } from '../../knowledge-graph/knowledgeGraphStore';
import type {
  GeneratedSectionDraft,
  ImportSummaryReport,
  LlmRoutingAuditReport,
  MappedProtocolSection,
  SectionImportDiagnostics,
  SuspiciousMappingRecord,
} from './types';
import { inferWorkflowState } from './sectionWorkflowState';

export function buildImportSummaryReport(input: {
  mappings: MappedProtocolSection[];
  suspiciousMappings: SuspiciousMappingRecord[];
  needsGenerationSectionIds: string[];
  sectionDrafts: Record<string, GeneratedSectionDraft>;
  sectionGenerationStates: Record<string, SectionGenerationState>;
  generationSchedule: GenerationAgentOutput;
  diagnostics: Record<string, SectionImportDiagnostics>;
}): ImportSummaryReport {
  const drafts = Object.values(input.sectionDrafts);
  const importedSections = drafts.filter((draft) => draft.contentOrigin === 'imported').length;
  const generatedSections = drafts.filter((draft) => draft.contentOrigin === 'generated').length;
  const validatedSections = drafts.filter((draft) => {
    const workflow = inferWorkflowState(draft);
    return workflow === 'validated' || workflow === 'reviewed' || draft.state === 'approved';
  }).length;
  const graph = getKnowledgeGraph();

  return {
    capturedAt: new Date().toISOString(),
    importedSections,
    validatedSections,
    generatedSections,
    needsGeneration: input.needsGenerationSectionIds.length,
    suspiciousMappings: input.suspiciousMappings.length,
    noMatch: input.diagnostics
      ? Object.values(input.diagnostics).filter((entry) => entry.mappingStatus === 'noMatch').length
      : 0,
    orphanSections: Object.keys(input.diagnostics).length,
    knowledgeGraphEntities: graph?.entities.length ?? 0,
    knowledgeGraphRelationships: graph?.relationships.length ?? 0,
    generationQueued: input.generationSchedule.prioritizedSections.length + input.generationSchedule.backgroundSections.length,
    generationSkipped: input.generationSchedule.skippedSections.length,
    mappedSections: input.mappings.length,
  };
}

export function buildLlmRoutingAuditReport(input: {
  mappings: MappedProtocolSection[];
  sectionDrafts: Record<string, GeneratedSectionDraft>;
  needsGenerationSectionIds: string[];
  generationSchedule: GenerationAgentOutput;
}): LlmRoutingAuditReport {
  const mappedDeterministically = input.mappings.filter(
    (mapping) => mapping.mappingMethod !== 'llm' && mapping.mappingMethod !== 'semantic-llm',
  );
  const generatedByLlm = Object.values(input.sectionDrafts).filter(
    (draft) =>
      draft.contentOrigin === 'generated' &&
      (draft.generationProvider === 'openai' || draft.provenance.generationModel?.includes('gpt')),
  );
  const generatedByLocal = Object.values(input.sectionDrafts).filter(
    (draft) =>
      draft.contentOrigin === 'generated' &&
      (draft.generationProvider === 'fixture' || draft.generationProvider === 'local-deterministic'),
  );

  const unnecessaryLlmCandidates = input.needsGenerationSectionIds
    .filter((sectionId) => !input.generationSchedule.prioritizedSections.includes(sectionId))
    .map((sectionId) => ({
      sectionId,
      reason:
        input.generationSchedule.skippedSections.find((entry) => entry.sectionId === sectionId)?.reason ??
        'Skipped by generation schedule',
    }));

  return {
    capturedAt: new Date().toISOString(),
    mappedDeterministically: mappedDeterministically.length,
    generatedByLlm: generatedByLlm.length,
    generatedByLocalDeterministic: generatedByLocal.length,
    unnecessaryLlmRouting: unnecessaryLlmCandidates,
  };
}

export function formatImportSummaryLines(summary: ImportSummaryReport): string[] {
  return [
    `Imported Sections: ${summary.importedSections}`,
    `Validated Sections: ${summary.validatedSections}`,
    `Generated Sections: ${summary.generatedSections}`,
    `Needs Generation: ${summary.needsGeneration}`,
    `Suspicious Mappings: ${summary.suspiciousMappings}`,
    `No Match: ${summary.noMatch}`,
    '',
    'Knowledge Graph:',
    `${summary.knowledgeGraphEntities} entities`,
    `${summary.knowledgeGraphRelationships} relationships`,
    '',
    'Generation Agent:',
    `${summary.generationQueued} queued`,
    `${summary.generationSkipped} skipped`,
  ];
}

export function formatLlmRoutingAuditLines(audit: LlmRoutingAuditReport): string[] {
  return [
    `Mapped Deterministically: ${audit.mappedDeterministically}`,
    `Generated by LLM: ${audit.generatedByLlm}`,
    `Generated by Local Deterministic: ${audit.generatedByLocalDeterministic}`,
    ...(audit.unnecessaryLlmRouting.length > 0
      ? [
          '',
          'Potential unnecessary LLM routing:',
          ...audit.unnecessaryLlmRouting.slice(0, 8).map((entry) => `${entry.sectionId}: ${entry.reason}`),
        ]
      : []),
  ];
}
