/**
 * Static ICH M11 Controlled Terminology (NCI EVS).
 * Generated by scripts/ingest-ich-m11-terminology.ts — do not edit JSON by hand.
 */

import terminologyDocument from './data/ichM11ControlledTerminology.json';

export interface M11ControlledTerm {
  code: string;
  ichPreferredTerm: string;
  preferredTerm: string;
  definition: string;
}

export interface M11Codelist {
  id: string;
  oid: string;
  name: string;
  preferredTerm: string;
  extensible: boolean;
  dataType: string;
  ichDefinition?: string;
  terms: M11ControlledTerm[];
}

export interface M11ControlledTerminologyDocument {
  source: string;
  name: string;
  terminologyDate: string;
  sourceUrl: string;
  loadedAt: string;
  ingestionMode: 'full' | 'partial';
  codelists: M11Codelist[];
}

export const ICH_M11_TERMINOLOGY_META = {
  documentKind: 'controlled-terminology' as const,
  title: terminologyDocument.name,
  version: `NCI EVS (${terminologyDocument.terminologyDate})`,
  status: 'static-local' as const,
  sourceFilename: 'ichM11ControlledTerminology.json',
  sourceUrl: terminologyDocument.sourceUrl,
  terminologyDate: terminologyDocument.terminologyDate,
  loadedAt: terminologyDocument.loadedAt,
  ingestionMode: terminologyDocument.ingestionMode,
  description:
    'ICH M11 controlled terminology codelists and terms for validation scaffolding and harmonized dropdowns.',
  incompleteAreas:
    terminologyDocument.ingestionMode === 'partial'
      ? ['Partial codelist ingest — run ingest script for full EVS extract.']
      : [],
};

const DOCUMENT = terminologyDocument as M11ControlledTerminologyDocument;

const CODELIST_BY_ID = new Map<string, M11Codelist>();
const CODELIST_BY_NAME = new Map<string, M11Codelist>();

for (const codelist of DOCUMENT.codelists) {
  CODELIST_BY_ID.set(codelist.id, codelist);
  CODELIST_BY_ID.set(codelist.oid, codelist);
  CODELIST_BY_NAME.set(normalizeKey(codelist.name), codelist);
  CODELIST_BY_NAME.set(normalizeKey(codelist.preferredTerm), codelist);
}

function normalizeKey(value: string): string {
  return value.toLowerCase().replace(/\s+/g, ' ').trim();
}

export function getM11ControlledTerminologyDocument(): M11ControlledTerminologyDocument {
  return DOCUMENT;
}

export function getM11CodelistCount(): number {
  return DOCUMENT.codelists.length;
}

export function getM11TermCount(): number {
  return DOCUMENT.codelists.reduce((sum, list) => sum + list.terms.length, 0);
}

/** Returns all M11 codelists. */
export function getM11Codelists(): M11Codelist[] {
  return DOCUMENT.codelists;
}

/** Resolves a codelist by NCI id (e.g. C217045), OID (CL.C217045...), or name. */
export function getM11Codelist(idOrName: string): M11Codelist | undefined {
  return (
    CODELIST_BY_ID.get(idOrName) ??
    CODELIST_BY_NAME.get(normalizeKey(idOrName)) ??
    DOCUMENT.codelists.find((list) => normalizeKey(list.name).includes(normalizeKey(idOrName)))
  );
}

export interface M11TermMatch {
  codelist: M11Codelist;
  term: M11ControlledTerm;
}

function matchesTerm(term: M11ControlledTerm, value: string): boolean {
  const normalized = normalizeKey(value);
  return (
    normalizeKey(term.code) === normalized ||
    normalizeKey(term.ichPreferredTerm) === normalized ||
    normalizeKey(term.preferredTerm) === normalized
  );
}

/** Finds a term within a codelist by code or label (case-insensitive). */
export function findM11Term(codelistIdOrName: string, value: string): M11TermMatch | undefined {
  const codelist = getM11Codelist(codelistIdOrName);
  if (!codelist || !value.trim()) {
    return undefined;
  }
  const term = codelist.terms.find((item) => matchesTerm(item, value));
  return term ? { codelist, term } : undefined;
}

export interface M11ControlledTermValidationResult {
  valid: boolean;
  codelistId?: string;
  codelistName?: string;
  matchedTerm?: M11ControlledTerm;
  message: string;
  suggestedValues: string[];
}

/** Non-blocking validation — returns pass/fail with suggested allowed values. */
export function validateM11ControlledTerm(
  codelistIdOrName: string,
  value: string,
): M11ControlledTermValidationResult {
  const codelist = getM11Codelist(codelistIdOrName);
  const suggestedValues = codelist?.terms.map((term) => term.ichPreferredTerm) ?? [];

  if (!codelist) {
    return {
      valid: false,
      message: `Unknown M11 codelist: ${codelistIdOrName}`,
      suggestedValues: [],
    };
  }

  if (!value?.trim()) {
    return {
      valid: false,
      codelistId: codelist.id,
      codelistName: codelist.name,
      message: 'Value is required.',
      suggestedValues,
    };
  }

  const match = findM11Term(codelist.id, value);
  if (match) {
    return {
      valid: true,
      codelistId: codelist.id,
      codelistName: codelist.name,
      matchedTerm: match.term,
      message: 'Term matches ICH M11 controlled terminology.',
      suggestedValues,
    };
  }

  return {
    valid: false,
    codelistId: codelist.id,
    codelistName: codelist.name,
    message: `"${value}" is not a recognized term in ${codelist.name}.`,
    suggestedValues,
  };
}

/** Dropdown values for protocol fields bound to an NCI codelist id. */
export function getM11CodelistDropdownValues(
  codelistId: string,
): Array<string | { label: string; code: string }> {
  const codelist = getM11Codelist(codelistId);
  if (!codelist) {
    return [];
  }
  return codelist.terms.map((term) => ({
    label: term.ichPreferredTerm,
    code: term.code,
  }));
}

export function searchM11Terminology(query: string, codelistFilter?: string): Array<{
  codelist: M11Codelist;
  term: M11ControlledTerm;
}> {
  const normalizedQuery = normalizeKey(query);
  if (!normalizedQuery) {
    return [];
  }

  const lists = codelistFilter
    ? [getM11Codelist(codelistFilter)].filter((list): list is M11Codelist => list !== undefined)
    : DOCUMENT.codelists;

  const results: Array<{ codelist: M11Codelist; term: M11ControlledTerm }> = [];

  for (const codelist of lists) {
    if (
      normalizeKey(codelist.name).includes(normalizedQuery) ||
      normalizeKey(codelist.preferredTerm).includes(normalizedQuery)
    ) {
      for (const term of codelist.terms) {
        results.push({ codelist, term });
      }
      continue;
    }
    for (const term of codelist.terms) {
      if (
        normalizeKey(term.ichPreferredTerm).includes(normalizedQuery) ||
        normalizeKey(term.preferredTerm).includes(normalizedQuery) ||
        normalizeKey(term.definition).includes(normalizedQuery) ||
        term.code.toLowerCase().includes(normalizedQuery)
      ) {
        results.push({ codelist, term });
      }
    }
  }

  return results;
}
